# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160801_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to=b''),
        ),
    ]
