# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='slug', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to=b''),
        ),
    ]
